In [87]:
import numpy as np
size=int(input("Enter the size of the square matrix :"))
A=[[0]*size]*size
B=[[0]*size]*size
C=[[0]*size]*size

print("Enter the elements of matrix A")
A=np.asarray(A)
B=np.asarray(B)
C=np.asarray(C)

Enter the size of the square matrix :2
Enter the elements of matrix A


In [88]:
for i in range(size):
    for j in range(size):
        A[i][j]=int(input("Enter the element ["+str(i+1)+" "+str(j+1)+"] :"))

print("Enter the elements of matrix B")
print()
for i in range(size):
    for j in range(size):
        B[i][j]=int(input("Enter the element ["+str(i+1)+" "+str(j+1)+"] :"))


Enter the element [1 1] :1
Enter the element [1 2] :2
Enter the element [2 1] :3
Enter the element [2 2] :4
Enter the elements of matrix B

Enter the element [1 1] :2
Enter the element [1 2] :0
Enter the element [2 1] :1
Enter the element [2 2] :2
[[2 0]
 [1 2]]


In [89]:

for i in range(size):
    for j in range(size):
        for k in range(size):
            C[i][j]=C[i][j]+A[i][k]*B[k][j]
print("C= A*B")
print(C)

[[1 2]
 [3 4]]
[[2 0]
 [1 2]]
C= A*B
[[ 4  4]
 [10  8]]
